name: Publish @stradox/paystack to jsr
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup Deno
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: deno test --allow-env --allow-net

      - name: Publish package
        run: deno publish