name: Test @stradox/paystack Package

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          
      - name: Test with Deno
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: deno test --allow-env --allow-net